"""Installation-specific paths and measured calibration; no fabricated receipts."""
import argparse
import hashlib
import json
import os
from pathlib import Path

from .paths import CODE, ROOT, save_json


FIELDS = {
    "move_amplitude": "selected_amplitude", "nominal_step_m": "nominal_step_m",
    "token_vectors": "suggested_token_vectors", "wrist_extra_flip": "wrist_extra_flip",
    "move_env_steps": "move_env_steps", "gripper_env_steps": "gripper_env_steps",
    "empty_width_m": "empty_width_m", "open_width_m": "open_width_m",
    "effective_table_height_m": "effective_table_height_m",
}


def layout():
    import yaml
    base = CODE.parent / "LIBERO/libero"
    if not (base / "libero/bddl_files").is_dir():
        raise ValueError("Install the pinned LIBERO checkout first")
    directory = Path(os.environ.get("LIBERO_CONFIG_PATH", ROOT / "configs/libero"))
    config = {name: str(path.resolve()) for name, path in {
        "benchmark_root": base / "libero", "bddl_files": base / "libero/bddl_files",
        "init_states": base / "libero/init_files", "assets": base / "libero/assets",
        "datasets": base / "datasets",
    }.items()}
    target = directory / "config.yaml"
    if target.exists():
        if yaml.safe_load(target.read_text()) != config:
            raise ValueError("Existing LIBERO configuration differs; preserve it and inspect")
        return target
    directory.mkdir(parents=True, exist_ok=True)
    with target.open("x") as handle:
        yaml.safe_dump(config, handle)
    for stage in ("wla-stage1", "rua-stage2", "rua-stage3"):
        (ROOT / "artifacts" / stage).mkdir(parents=True, exist_ok=True)
    return target


def accept_calibration(receipt):
    receipt = receipt.resolve()
    report = json.loads(receipt.read_text())
    if (report.get("status") != "passed" or report.get("torch_cuda_initialized")
            or report.get("scope") != "robot_camera_control_calibration_not_evaluation"):
        raise ValueError("A successful local physical calibration is required")
    if (not receipt.is_relative_to((ROOT / "artifacts/rua-stage2").resolve())
            or report.get("installation_code_root") != str(CODE.resolve())
            or report.get("calibration_source_sha256") != hashlib.sha256(
                (CODE / "libero_harness/calibrate.py").read_bytes()).hexdigest()):
        raise ValueError("Calibration must be freshly generated by this installation")
    config = {setting: report[measurement] for setting, measurement in FIELDS.items()}
    config.update(calibration_status="passed", calibration_receipt=str(receipt),
                  calibration_sha256=hashlib.sha256(receipt.read_bytes()).hexdigest())
    target = Path(os.environ.get("RUA_AGENT_CONFIG", ROOT / "configs/agent.local.json"))
    if target.exists():
        raise FileExistsError("Preserve the previous local configuration; choose a new RUA_AGENT_CONFIG")
    target.parent.mkdir(parents=True, exist_ok=True)
    with target.open("x") as handle:
        json.dump(config, handle, indent=2)
    target.chmod(0o600)
    return target


def main():
    parser = argparse.ArgumentParser()
    sub = parser.add_subparsers(dest="mode", required=True)
    sub.add_parser("layout")
    p = sub.add_parser("accept-calibration")
    p.add_argument("receipt", type=Path)
    args = parser.parse_args()
    path = layout() if args.mode == "layout" else accept_calibration(args.receipt)
    print(json.dumps(dict(status="prepared", path=str(path))))


if __name__ == "__main__":
    main()
